// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderData.proto

#ifndef PROTOBUF_orderData_2eproto__INCLUDED
#define PROTOBUF_orderData_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace comm {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_orderData_2eproto();
void protobuf_AssignDesc_orderData_2eproto();
void protobuf_ShutdownFile_orderData_2eproto();

class OrderData;

// ===================================================================

class OrderData : public ::google::protobuf::Message {
 public:
  OrderData();
  virtual ~OrderData();

  OrderData(const OrderData& from);

  inline OrderData& operator=(const OrderData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrderData& default_instance();

  void Swap(OrderData* other);

  // implements Message ----------------------------------------------

  OrderData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OrderData& from);
  void MergeFrom(const OrderData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string WindCode = 1;
  inline bool has_windcode() const;
  inline void clear_windcode();
  static const int kWindCodeFieldNumber = 1;
  inline const ::std::string& windcode() const;
  inline void set_windcode(const ::std::string& value);
  inline void set_windcode(const char* value);
  inline void set_windcode(const char* value, size_t size);
  inline ::std::string* mutable_windcode();
  inline ::std::string* release_windcode();
  inline void set_allocated_windcode(::std::string* windcode);

  // required string Code = 2;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 2;
  inline const ::std::string& code() const;
  inline void set_code(const ::std::string& value);
  inline void set_code(const char* value);
  inline void set_code(const char* value, size_t size);
  inline ::std::string* mutable_code();
  inline ::std::string* release_code();
  inline void set_allocated_code(::std::string* code);

  // required int32 ActionDay = 3;
  inline bool has_actionday() const;
  inline void clear_actionday();
  static const int kActionDayFieldNumber = 3;
  inline ::google::protobuf::int32 actionday() const;
  inline void set_actionday(::google::protobuf::int32 value);

  // required int32 Time = 4;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 4;
  inline ::google::protobuf::int32 time() const;
  inline void set_time(::google::protobuf::int32 value);

  // required int32 Order = 5;
  inline bool has_order() const;
  inline void clear_order();
  static const int kOrderFieldNumber = 5;
  inline ::google::protobuf::int32 order() const;
  inline void set_order(::google::protobuf::int32 value);

  // required int32 Price = 6;
  inline bool has_price() const;
  inline void clear_price();
  static const int kPriceFieldNumber = 6;
  inline ::google::protobuf::int32 price() const;
  inline void set_price(::google::protobuf::int32 value);

  // required int32 Volume = 7;
  inline bool has_volume() const;
  inline void clear_volume();
  static const int kVolumeFieldNumber = 7;
  inline ::google::protobuf::int32 volume() const;
  inline void set_volume(::google::protobuf::int32 value);

  // required string OrderKind = 8;
  inline bool has_orderkind() const;
  inline void clear_orderkind();
  static const int kOrderKindFieldNumber = 8;
  inline const ::std::string& orderkind() const;
  inline void set_orderkind(const ::std::string& value);
  inline void set_orderkind(const char* value);
  inline void set_orderkind(const char* value, size_t size);
  inline ::std::string* mutable_orderkind();
  inline ::std::string* release_orderkind();
  inline void set_allocated_orderkind(::std::string* orderkind);

  // required string FunctionCode = 9;
  inline bool has_functioncode() const;
  inline void clear_functioncode();
  static const int kFunctionCodeFieldNumber = 9;
  inline const ::std::string& functioncode() const;
  inline void set_functioncode(const ::std::string& value);
  inline void set_functioncode(const char* value);
  inline void set_functioncode(const char* value, size_t size);
  inline ::std::string* mutable_functioncode();
  inline ::std::string* release_functioncode();
  inline void set_allocated_functioncode(::std::string* functioncode);

  // @@protoc_insertion_point(class_scope:comm.OrderData)
 private:
  inline void set_has_windcode();
  inline void clear_has_windcode();
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_actionday();
  inline void clear_has_actionday();
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_order();
  inline void clear_has_order();
  inline void set_has_price();
  inline void clear_has_price();
  inline void set_has_volume();
  inline void clear_has_volume();
  inline void set_has_orderkind();
  inline void clear_has_orderkind();
  inline void set_has_functioncode();
  inline void clear_has_functioncode();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* windcode_;
  ::std::string* code_;
  ::google::protobuf::int32 actionday_;
  ::google::protobuf::int32 time_;
  ::google::protobuf::int32 order_;
  ::google::protobuf::int32 price_;
  ::std::string* orderkind_;
  ::std::string* functioncode_;
  ::google::protobuf::int32 volume_;
  friend void  protobuf_AddDesc_orderData_2eproto();
  friend void protobuf_AssignDesc_orderData_2eproto();
  friend void protobuf_ShutdownFile_orderData_2eproto();

  void InitAsDefaultInstance();
  static OrderData* default_instance_;
};
// ===================================================================


// ===================================================================

// OrderData

// required string WindCode = 1;
inline bool OrderData::has_windcode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OrderData::set_has_windcode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OrderData::clear_has_windcode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OrderData::clear_windcode() {
  if (windcode_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    windcode_->clear();
  }
  clear_has_windcode();
}
inline const ::std::string& OrderData::windcode() const {
  // @@protoc_insertion_point(field_get:comm.OrderData.WindCode)
  return *windcode_;
}
inline void OrderData::set_windcode(const ::std::string& value) {
  set_has_windcode();
  if (windcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    windcode_ = new ::std::string;
  }
  windcode_->assign(value);
  // @@protoc_insertion_point(field_set:comm.OrderData.WindCode)
}
inline void OrderData::set_windcode(const char* value) {
  set_has_windcode();
  if (windcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    windcode_ = new ::std::string;
  }
  windcode_->assign(value);
  // @@protoc_insertion_point(field_set_char:comm.OrderData.WindCode)
}
inline void OrderData::set_windcode(const char* value, size_t size) {
  set_has_windcode();
  if (windcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    windcode_ = new ::std::string;
  }
  windcode_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:comm.OrderData.WindCode)
}
inline ::std::string* OrderData::mutable_windcode() {
  set_has_windcode();
  if (windcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    windcode_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:comm.OrderData.WindCode)
  return windcode_;
}
inline ::std::string* OrderData::release_windcode() {
  clear_has_windcode();
  if (windcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = windcode_;
    windcode_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OrderData::set_allocated_windcode(::std::string* windcode) {
  if (windcode_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete windcode_;
  }
  if (windcode) {
    set_has_windcode();
    windcode_ = windcode;
  } else {
    clear_has_windcode();
    windcode_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:comm.OrderData.WindCode)
}

// required string Code = 2;
inline bool OrderData::has_code() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OrderData::set_has_code() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OrderData::clear_has_code() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OrderData::clear_code() {
  if (code_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    code_->clear();
  }
  clear_has_code();
}
inline const ::std::string& OrderData::code() const {
  // @@protoc_insertion_point(field_get:comm.OrderData.Code)
  return *code_;
}
inline void OrderData::set_code(const ::std::string& value) {
  set_has_code();
  if (code_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    code_ = new ::std::string;
  }
  code_->assign(value);
  // @@protoc_insertion_point(field_set:comm.OrderData.Code)
}
inline void OrderData::set_code(const char* value) {
  set_has_code();
  if (code_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    code_ = new ::std::string;
  }
  code_->assign(value);
  // @@protoc_insertion_point(field_set_char:comm.OrderData.Code)
}
inline void OrderData::set_code(const char* value, size_t size) {
  set_has_code();
  if (code_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    code_ = new ::std::string;
  }
  code_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:comm.OrderData.Code)
}
inline ::std::string* OrderData::mutable_code() {
  set_has_code();
  if (code_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    code_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:comm.OrderData.Code)
  return code_;
}
inline ::std::string* OrderData::release_code() {
  clear_has_code();
  if (code_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = code_;
    code_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OrderData::set_allocated_code(::std::string* code) {
  if (code_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete code_;
  }
  if (code) {
    set_has_code();
    code_ = code;
  } else {
    clear_has_code();
    code_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:comm.OrderData.Code)
}

// required int32 ActionDay = 3;
inline bool OrderData::has_actionday() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OrderData::set_has_actionday() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OrderData::clear_has_actionday() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OrderData::clear_actionday() {
  actionday_ = 0;
  clear_has_actionday();
}
inline ::google::protobuf::int32 OrderData::actionday() const {
  // @@protoc_insertion_point(field_get:comm.OrderData.ActionDay)
  return actionday_;
}
inline void OrderData::set_actionday(::google::protobuf::int32 value) {
  set_has_actionday();
  actionday_ = value;
  // @@protoc_insertion_point(field_set:comm.OrderData.ActionDay)
}

// required int32 Time = 4;
inline bool OrderData::has_time() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OrderData::set_has_time() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OrderData::clear_has_time() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OrderData::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline ::google::protobuf::int32 OrderData::time() const {
  // @@protoc_insertion_point(field_get:comm.OrderData.Time)
  return time_;
}
inline void OrderData::set_time(::google::protobuf::int32 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:comm.OrderData.Time)
}

// required int32 Order = 5;
inline bool OrderData::has_order() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void OrderData::set_has_order() {
  _has_bits_[0] |= 0x00000010u;
}
inline void OrderData::clear_has_order() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void OrderData::clear_order() {
  order_ = 0;
  clear_has_order();
}
inline ::google::protobuf::int32 OrderData::order() const {
  // @@protoc_insertion_point(field_get:comm.OrderData.Order)
  return order_;
}
inline void OrderData::set_order(::google::protobuf::int32 value) {
  set_has_order();
  order_ = value;
  // @@protoc_insertion_point(field_set:comm.OrderData.Order)
}

// required int32 Price = 6;
inline bool OrderData::has_price() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void OrderData::set_has_price() {
  _has_bits_[0] |= 0x00000020u;
}
inline void OrderData::clear_has_price() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void OrderData::clear_price() {
  price_ = 0;
  clear_has_price();
}
inline ::google::protobuf::int32 OrderData::price() const {
  // @@protoc_insertion_point(field_get:comm.OrderData.Price)
  return price_;
}
inline void OrderData::set_price(::google::protobuf::int32 value) {
  set_has_price();
  price_ = value;
  // @@protoc_insertion_point(field_set:comm.OrderData.Price)
}

// required int32 Volume = 7;
inline bool OrderData::has_volume() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void OrderData::set_has_volume() {
  _has_bits_[0] |= 0x00000040u;
}
inline void OrderData::clear_has_volume() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void OrderData::clear_volume() {
  volume_ = 0;
  clear_has_volume();
}
inline ::google::protobuf::int32 OrderData::volume() const {
  // @@protoc_insertion_point(field_get:comm.OrderData.Volume)
  return volume_;
}
inline void OrderData::set_volume(::google::protobuf::int32 value) {
  set_has_volume();
  volume_ = value;
  // @@protoc_insertion_point(field_set:comm.OrderData.Volume)
}

// required string OrderKind = 8;
inline bool OrderData::has_orderkind() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void OrderData::set_has_orderkind() {
  _has_bits_[0] |= 0x00000080u;
}
inline void OrderData::clear_has_orderkind() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void OrderData::clear_orderkind() {
  if (orderkind_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    orderkind_->clear();
  }
  clear_has_orderkind();
}
inline const ::std::string& OrderData::orderkind() const {
  // @@protoc_insertion_point(field_get:comm.OrderData.OrderKind)
  return *orderkind_;
}
inline void OrderData::set_orderkind(const ::std::string& value) {
  set_has_orderkind();
  if (orderkind_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    orderkind_ = new ::std::string;
  }
  orderkind_->assign(value);
  // @@protoc_insertion_point(field_set:comm.OrderData.OrderKind)
}
inline void OrderData::set_orderkind(const char* value) {
  set_has_orderkind();
  if (orderkind_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    orderkind_ = new ::std::string;
  }
  orderkind_->assign(value);
  // @@protoc_insertion_point(field_set_char:comm.OrderData.OrderKind)
}
inline void OrderData::set_orderkind(const char* value, size_t size) {
  set_has_orderkind();
  if (orderkind_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    orderkind_ = new ::std::string;
  }
  orderkind_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:comm.OrderData.OrderKind)
}
inline ::std::string* OrderData::mutable_orderkind() {
  set_has_orderkind();
  if (orderkind_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    orderkind_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:comm.OrderData.OrderKind)
  return orderkind_;
}
inline ::std::string* OrderData::release_orderkind() {
  clear_has_orderkind();
  if (orderkind_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = orderkind_;
    orderkind_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OrderData::set_allocated_orderkind(::std::string* orderkind) {
  if (orderkind_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete orderkind_;
  }
  if (orderkind) {
    set_has_orderkind();
    orderkind_ = orderkind;
  } else {
    clear_has_orderkind();
    orderkind_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:comm.OrderData.OrderKind)
}

// required string FunctionCode = 9;
inline bool OrderData::has_functioncode() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void OrderData::set_has_functioncode() {
  _has_bits_[0] |= 0x00000100u;
}
inline void OrderData::clear_has_functioncode() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void OrderData::clear_functioncode() {
  if (functioncode_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    functioncode_->clear();
  }
  clear_has_functioncode();
}
inline const ::std::string& OrderData::functioncode() const {
  // @@protoc_insertion_point(field_get:comm.OrderData.FunctionCode)
  return *functioncode_;
}
inline void OrderData::set_functioncode(const ::std::string& value) {
  set_has_functioncode();
  if (functioncode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    functioncode_ = new ::std::string;
  }
  functioncode_->assign(value);
  // @@protoc_insertion_point(field_set:comm.OrderData.FunctionCode)
}
inline void OrderData::set_functioncode(const char* value) {
  set_has_functioncode();
  if (functioncode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    functioncode_ = new ::std::string;
  }
  functioncode_->assign(value);
  // @@protoc_insertion_point(field_set_char:comm.OrderData.FunctionCode)
}
inline void OrderData::set_functioncode(const char* value, size_t size) {
  set_has_functioncode();
  if (functioncode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    functioncode_ = new ::std::string;
  }
  functioncode_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:comm.OrderData.FunctionCode)
}
inline ::std::string* OrderData::mutable_functioncode() {
  set_has_functioncode();
  if (functioncode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    functioncode_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:comm.OrderData.FunctionCode)
  return functioncode_;
}
inline ::std::string* OrderData::release_functioncode() {
  clear_has_functioncode();
  if (functioncode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = functioncode_;
    functioncode_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OrderData::set_allocated_functioncode(::std::string* functioncode) {
  if (functioncode_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete functioncode_;
  }
  if (functioncode) {
    set_has_functioncode();
    functioncode_ = functioncode;
  } else {
    clear_has_functioncode();
    functioncode_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:comm.OrderData.FunctionCode)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace comm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_orderData_2eproto__INCLUDED
