// Code generated by protoc-gen-go.
// source: factor.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	factor.proto

It has these top-level messages:
	FactorResult
	FactorResults
	FactorResp
*/
package pb

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type FactorResult struct {
	ResultKey        *string  `protobuf:"bytes,1,req" json:"ResultKey,omitempty"`
	ResultValue      *float64 `protobuf:"fixed64,2,req" json:"ResultValue,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FactorResult) Reset()         { *m = FactorResult{} }
func (m *FactorResult) String() string { return proto.CompactTextString(m) }
func (*FactorResult) ProtoMessage()    {}

func (m *FactorResult) GetResultKey() string {
	if m != nil && m.ResultKey != nil {
		return *m.ResultKey
	}
	return ""
}

func (m *FactorResult) GetResultValue() float64 {
	if m != nil && m.ResultValue != nil {
		return *m.ResultValue
	}
	return 0
}

type FactorResults struct {
	Result           []*FactorResult `protobuf:"bytes,1,rep" json:"Result,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *FactorResults) Reset()         { *m = FactorResults{} }
func (m *FactorResults) String() string { return proto.CompactTextString(m) }
func (*FactorResults) ProtoMessage()    {}

func (m *FactorResults) GetResult() []*FactorResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type FactorResp struct {
	Results          []*FactorResults `protobuf:"bytes,1,rep" json:"Results,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *FactorResp) Reset()         { *m = FactorResp{} }
func (m *FactorResp) String() string { return proto.CompactTextString(m) }
func (*FactorResp) ProtoMessage()    {}

func (m *FactorResp) GetResults() []*FactorResults {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
}
