// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	User
*/
package pb

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ACCOUNT_TYPE int32

const (
	ACCOUNT_TYPE_ACCOUNT_TYPE_ROOT        ACCOUNT_TYPE = 0
	ACCOUNT_TYPE_ACCOUNT_TYPE_USER        ACCOUNT_TYPE = 1
	ACCOUNT_TYPE_ACCOUNT_TYPE_INSTITUTION ACCOUNT_TYPE = 2
)

var ACCOUNT_TYPE_name = map[int32]string{
	0: "ACCOUNT_TYPE_ROOT",
	1: "ACCOUNT_TYPE_USER",
	2: "ACCOUNT_TYPE_INSTITUTION",
}
var ACCOUNT_TYPE_value = map[string]int32{
	"ACCOUNT_TYPE_ROOT":        0,
	"ACCOUNT_TYPE_USER":        1,
	"ACCOUNT_TYPE_INSTITUTION": 2,
}

func (x ACCOUNT_TYPE) Enum() *ACCOUNT_TYPE {
	p := new(ACCOUNT_TYPE)
	*p = x
	return p
}
func (x ACCOUNT_TYPE) String() string {
	return proto.EnumName(ACCOUNT_TYPE_name, int32(x))
}
func (x *ACCOUNT_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ACCOUNT_TYPE_value, data, "ACCOUNT_TYPE")
	if err != nil {
		return err
	}
	*x = ACCOUNT_TYPE(value)
	return nil
}

type User struct {
	// 用户名
	UserName *string `protobuf:"bytes,1,req" json:"UserName,omitempty"`
	// 密码
	PassWord *string `protobuf:"bytes,2,req" json:"PassWord,omitempty"`
	// 中文姓名
	ChineseName *string `protobuf:"bytes,3,req" json:"ChineseName,omitempty"`
	// 可用资金
	AvailableMoney *string `protobuf:"bytes,4,req" json:"AvailableMoney,omitempty"`
	// 停机位
	StopLost *string `protobuf:"bytes,5,req" json:"StopLost,omitempty"`
	// 单笔最大股数
	VolumeLimit *int32 `protobuf:"varint,6,req" json:"VolumeLimit,omitempty"`
	// 单笔最大金额
	MonetaryLimit *float32 `protobuf:"fixed32,7,req" json:"MonetaryLimit,omitempty"`
	// 状态，０：停用，１启用
	Status *int32 `protobuf:"varint,8,req" json:"Status,omitempty"`
	// 账号类型
	AccountType      *ACCOUNT_TYPE `protobuf:"varint,9,req,enum=pb.ACCOUNT_TYPE" json:"AccountType,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

func (m *User) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *User) GetPassWord() string {
	if m != nil && m.PassWord != nil {
		return *m.PassWord
	}
	return ""
}

func (m *User) GetChineseName() string {
	if m != nil && m.ChineseName != nil {
		return *m.ChineseName
	}
	return ""
}

func (m *User) GetAvailableMoney() string {
	if m != nil && m.AvailableMoney != nil {
		return *m.AvailableMoney
	}
	return ""
}

func (m *User) GetStopLost() string {
	if m != nil && m.StopLost != nil {
		return *m.StopLost
	}
	return ""
}

func (m *User) GetVolumeLimit() int32 {
	if m != nil && m.VolumeLimit != nil {
		return *m.VolumeLimit
	}
	return 0
}

func (m *User) GetMonetaryLimit() float32 {
	if m != nil && m.MonetaryLimit != nil {
		return *m.MonetaryLimit
	}
	return 0
}

func (m *User) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *User) GetAccountType() ACCOUNT_TYPE {
	if m != nil && m.AccountType != nil {
		return *m.AccountType
	}
	return ACCOUNT_TYPE_ACCOUNT_TYPE_ROOT
}

func init() {
	proto.RegisterEnum("pb.ACCOUNT_TYPE", ACCOUNT_TYPE_name, ACCOUNT_TYPE_value)
}
