// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MDBond.proto

package com_htsc_mdc_model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//债券信息
type MDBond struct {
	HTSCSecurityID        string            `protobuf:"bytes,1,opt,name=HTSCSecurityID,proto3" json:"HTSCSecurityID,omitempty"`
	MDDate                int32             `protobuf:"varint,2,opt,name=MDDate,proto3" json:"MDDate,omitempty"`
	MDTime                int32             `protobuf:"varint,3,opt,name=MDTime,proto3" json:"MDTime,omitempty"`
	DataTimestamp         int64             `protobuf:"varint,4,opt,name=DataTimestamp,proto3" json:"DataTimestamp,omitempty"`
	TradingPhaseCode      string            `protobuf:"bytes,5,opt,name=TradingPhaseCode,proto3" json:"TradingPhaseCode,omitempty"`
	SecurityIDSource      ESecurityIDSource `protobuf:"varint,6,opt,name=securityIDSource,proto3,enum=com.htsc.mdc.model.ESecurityIDSource" json:"securityIDSource,omitempty"`
	SecurityType          ESecurityType     `protobuf:"varint,7,opt,name=securityType,proto3,enum=com.htsc.mdc.model.ESecurityType" json:"securityType,omitempty"`
	MaxPx                 int64             `protobuf:"varint,8,opt,name=MaxPx,proto3" json:"MaxPx,omitempty"`
	MinPx                 int64             `protobuf:"varint,9,opt,name=MinPx,proto3" json:"MinPx,omitempty"`
	PreClosePx            int64             `protobuf:"varint,10,opt,name=PreClosePx,proto3" json:"PreClosePx,omitempty"`
	NumTrades             int64             `protobuf:"varint,11,opt,name=NumTrades,proto3" json:"NumTrades,omitempty"`
	TotalVolumeTrade      int64             `protobuf:"varint,12,opt,name=TotalVolumeTrade,proto3" json:"TotalVolumeTrade,omitempty"`
	TotalValueTrade       int64             `protobuf:"varint,13,opt,name=TotalValueTrade,proto3" json:"TotalValueTrade,omitempty"`
	LastPx                int64             `protobuf:"varint,14,opt,name=LastPx,proto3" json:"LastPx,omitempty"`
	OpenPx                int64             `protobuf:"varint,15,opt,name=OpenPx,proto3" json:"OpenPx,omitempty"`
	ClosePx               int64             `protobuf:"varint,16,opt,name=ClosePx,proto3" json:"ClosePx,omitempty"`
	HighPx                int64             `protobuf:"varint,17,opt,name=HighPx,proto3" json:"HighPx,omitempty"`
	LowPx                 int64             `protobuf:"varint,18,opt,name=LowPx,proto3" json:"LowPx,omitempty"`
	DiffPx1               int64             `protobuf:"varint,19,opt,name=DiffPx1,proto3" json:"DiffPx1,omitempty"`
	DiffPx2               int64             `protobuf:"varint,20,opt,name=DiffPx2,proto3" json:"DiffPx2,omitempty"`
	TotalBuyQty           int64             `protobuf:"varint,21,opt,name=TotalBuyQty,proto3" json:"TotalBuyQty,omitempty"`
	TotalSellQty          int64             `protobuf:"varint,22,opt,name=TotalSellQty,proto3" json:"TotalSellQty,omitempty"`
	WeightedAvgBuyPx      int64             `protobuf:"varint,23,opt,name=WeightedAvgBuyPx,proto3" json:"WeightedAvgBuyPx,omitempty"`
	WeightedAvgSellPx     int64             `protobuf:"varint,24,opt,name=WeightedAvgSellPx,proto3" json:"WeightedAvgSellPx,omitempty"`
	WithdrawBuyNumber     int64             `protobuf:"varint,25,opt,name=WithdrawBuyNumber,proto3" json:"WithdrawBuyNumber,omitempty"`
	WithdrawBuyAmount     int64             `protobuf:"varint,26,opt,name=WithdrawBuyAmount,proto3" json:"WithdrawBuyAmount,omitempty"`
	WithdrawBuyMoney      int64             `protobuf:"varint,27,opt,name=WithdrawBuyMoney,proto3" json:"WithdrawBuyMoney,omitempty"`
	WithdrawSellNumber    int64             `protobuf:"varint,28,opt,name=WithdrawSellNumber,proto3" json:"WithdrawSellNumber,omitempty"`
	WithdrawSellAmount    int64             `protobuf:"varint,29,opt,name=WithdrawSellAmount,proto3" json:"WithdrawSellAmount,omitempty"`
	WithdrawSellMoney     int64             `protobuf:"varint,30,opt,name=WithdrawSellMoney,proto3" json:"WithdrawSellMoney,omitempty"`
	TotalBuyNumber        int64             `protobuf:"varint,31,opt,name=TotalBuyNumber,proto3" json:"TotalBuyNumber,omitempty"`
	TotalSellNumber       int64             `protobuf:"varint,32,opt,name=TotalSellNumber,proto3" json:"TotalSellNumber,omitempty"`
	BuyTradeMaxDuration   int64             `protobuf:"varint,33,opt,name=BuyTradeMaxDuration,proto3" json:"BuyTradeMaxDuration,omitempty"`
	SellTradeMaxDuration  int64             `protobuf:"varint,34,opt,name=SellTradeMaxDuration,proto3" json:"SellTradeMaxDuration,omitempty"`
	NumBuyOrders          int32             `protobuf:"varint,35,opt,name=NumBuyOrders,proto3" json:"NumBuyOrders,omitempty"`
	NumSellOrders         int32             `protobuf:"varint,36,opt,name=NumSellOrders,proto3" json:"NumSellOrders,omitempty"`
	YieldToMaturity       int64             `protobuf:"varint,37,opt,name=YieldToMaturity,proto3" json:"YieldToMaturity,omitempty"`
	WeightedAvgPx         int64             `protobuf:"varint,38,opt,name=WeightedAvgPx,proto3" json:"WeightedAvgPx,omitempty"`
	WeightedAvgPxBP       int64             `protobuf:"varint,39,opt,name=WeightedAvgPxBP,proto3" json:"WeightedAvgPxBP,omitempty"`
	PreCloseWeightedAvgPx int64             `protobuf:"varint,40,opt,name=PreCloseWeightedAvgPx,proto3" json:"PreCloseWeightedAvgPx,omitempty"`
	ExchangeDate          int32             `protobuf:"varint,41,opt,name=ExchangeDate,proto3" json:"ExchangeDate,omitempty"`
	ExchangeTime          int32             `protobuf:"varint,42,opt,name=ExchangeTime,proto3" json:"ExchangeTime,omitempty"`
	PreCloseYield         int64             `protobuf:"varint,43,opt,name=PreCloseYield,proto3" json:"PreCloseYield,omitempty"`
	PreWeightedAvgYield   int64             `protobuf:"varint,44,opt,name=PreWeightedAvgYield,proto3" json:"PreWeightedAvgYield,omitempty"`
	OpenYield             int64             `protobuf:"varint,45,opt,name=OpenYield,proto3" json:"OpenYield,omitempty"`
	HighYield             int64             `protobuf:"varint,46,opt,name=HighYield,proto3" json:"HighYield,omitempty"`
	LowYield              int64             `protobuf:"varint,47,opt,name=LowYield,proto3" json:"LowYield,omitempty"`
	LastYield             int64             `protobuf:"varint,48,opt,name=LastYield,proto3" json:"LastYield,omitempty"`
	WeightedAvgYield      int64             `protobuf:"varint,49,opt,name=WeightedAvgYield,proto3" json:"WeightedAvgYield,omitempty"`
	ChannelNo             int32             `protobuf:"varint,50,opt,name=ChannelNo,proto3" json:"ChannelNo,omitempty"`
	BuyPriceQueue         []int64           `protobuf:"varint,51,rep,packed,name=BuyPriceQueue,proto3" json:"BuyPriceQueue,omitempty"`
	BuyOrderQtyQueue      []int64           `protobuf:"varint,52,rep,packed,name=BuyOrderQtyQueue,proto3" json:"BuyOrderQtyQueue,omitempty"`
	SellPriceQueue        []int64           `protobuf:"varint,53,rep,packed,name=SellPriceQueue,proto3" json:"SellPriceQueue,omitempty"`
	SellOrderQtyQueue     []int64           `protobuf:"varint,54,rep,packed,name=SellOrderQtyQueue,proto3" json:"SellOrderQtyQueue,omitempty"`
	BuyOrderQueue         []int64           `protobuf:"varint,55,rep,packed,name=BuyOrderQueue,proto3" json:"BuyOrderQueue,omitempty"`
	SellOrderQueue        []int64           `protobuf:"varint,56,rep,packed,name=SellOrderQueue,proto3" json:"SellOrderQueue,omitempty"`
	BuyNumOrdersQueue     []int64           `protobuf:"varint,57,rep,packed,name=BuyNumOrdersQueue,proto3" json:"BuyNumOrdersQueue,omitempty"`
	SellNumOrdersQueue    []int64           `protobuf:"varint,58,rep,packed,name=SellNumOrdersQueue,proto3" json:"SellNumOrdersQueue,omitempty"`
	NorminalPx            int64             `protobuf:"varint,59,opt,name=NorminalPx,proto3" json:"NorminalPx,omitempty"`
	ShortSellSharesTraded int64             `protobuf:"varint,60,opt,name=ShortSellSharesTraded,proto3" json:"ShortSellSharesTraded,omitempty"`
	ShortSellTurnover     int64             `protobuf:"varint,61,opt,name=ShortSellTurnover,proto3" json:"ShortSellTurnover,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}          `json:"-"`
	XXX_unrecognized      []byte            `json:"-"`
	XXX_sizecache         int32             `json:"-"`
}

func (m *MDBond) Reset()         { *m = MDBond{} }
func (m *MDBond) String() string { return proto.CompactTextString(m) }
func (*MDBond) ProtoMessage()    {}
func (*MDBond) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1e2a459aa62f2c, []int{0}
}

func (m *MDBond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MDBond.Unmarshal(m, b)
}
func (m *MDBond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MDBond.Marshal(b, m, deterministic)
}
func (m *MDBond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MDBond.Merge(m, src)
}
func (m *MDBond) XXX_Size() int {
	return xxx_messageInfo_MDBond.Size(m)
}
func (m *MDBond) XXX_DiscardUnknown() {
	xxx_messageInfo_MDBond.DiscardUnknown(m)
}

var xxx_messageInfo_MDBond proto.InternalMessageInfo

func (m *MDBond) GetHTSCSecurityID() string {
	if m != nil {
		return m.HTSCSecurityID
	}
	return ""
}

func (m *MDBond) GetMDDate() int32 {
	if m != nil {
		return m.MDDate
	}
	return 0
}

func (m *MDBond) GetMDTime() int32 {
	if m != nil {
		return m.MDTime
	}
	return 0
}

func (m *MDBond) GetDataTimestamp() int64 {
	if m != nil {
		return m.DataTimestamp
	}
	return 0
}

func (m *MDBond) GetTradingPhaseCode() string {
	if m != nil {
		return m.TradingPhaseCode
	}
	return ""
}

func (m *MDBond) GetSecurityIDSource() ESecurityIDSource {
	if m != nil {
		return m.SecurityIDSource
	}
	return ESecurityIDSource_DefaultSecurityIDSource
}

func (m *MDBond) GetSecurityType() ESecurityType {
	if m != nil {
		return m.SecurityType
	}
	return ESecurityType_DefaultSecurityType
}

func (m *MDBond) GetMaxPx() int64 {
	if m != nil {
		return m.MaxPx
	}
	return 0
}

func (m *MDBond) GetMinPx() int64 {
	if m != nil {
		return m.MinPx
	}
	return 0
}

func (m *MDBond) GetPreClosePx() int64 {
	if m != nil {
		return m.PreClosePx
	}
	return 0
}

func (m *MDBond) GetNumTrades() int64 {
	if m != nil {
		return m.NumTrades
	}
	return 0
}

func (m *MDBond) GetTotalVolumeTrade() int64 {
	if m != nil {
		return m.TotalVolumeTrade
	}
	return 0
}

func (m *MDBond) GetTotalValueTrade() int64 {
	if m != nil {
		return m.TotalValueTrade
	}
	return 0
}

func (m *MDBond) GetLastPx() int64 {
	if m != nil {
		return m.LastPx
	}
	return 0
}

func (m *MDBond) GetOpenPx() int64 {
	if m != nil {
		return m.OpenPx
	}
	return 0
}

func (m *MDBond) GetClosePx() int64 {
	if m != nil {
		return m.ClosePx
	}
	return 0
}

func (m *MDBond) GetHighPx() int64 {
	if m != nil {
		return m.HighPx
	}
	return 0
}

func (m *MDBond) GetLowPx() int64 {
	if m != nil {
		return m.LowPx
	}
	return 0
}

func (m *MDBond) GetDiffPx1() int64 {
	if m != nil {
		return m.DiffPx1
	}
	return 0
}

func (m *MDBond) GetDiffPx2() int64 {
	if m != nil {
		return m.DiffPx2
	}
	return 0
}

func (m *MDBond) GetTotalBuyQty() int64 {
	if m != nil {
		return m.TotalBuyQty
	}
	return 0
}

func (m *MDBond) GetTotalSellQty() int64 {
	if m != nil {
		return m.TotalSellQty
	}
	return 0
}

func (m *MDBond) GetWeightedAvgBuyPx() int64 {
	if m != nil {
		return m.WeightedAvgBuyPx
	}
	return 0
}

func (m *MDBond) GetWeightedAvgSellPx() int64 {
	if m != nil {
		return m.WeightedAvgSellPx
	}
	return 0
}

func (m *MDBond) GetWithdrawBuyNumber() int64 {
	if m != nil {
		return m.WithdrawBuyNumber
	}
	return 0
}

func (m *MDBond) GetWithdrawBuyAmount() int64 {
	if m != nil {
		return m.WithdrawBuyAmount
	}
	return 0
}

func (m *MDBond) GetWithdrawBuyMoney() int64 {
	if m != nil {
		return m.WithdrawBuyMoney
	}
	return 0
}

func (m *MDBond) GetWithdrawSellNumber() int64 {
	if m != nil {
		return m.WithdrawSellNumber
	}
	return 0
}

func (m *MDBond) GetWithdrawSellAmount() int64 {
	if m != nil {
		return m.WithdrawSellAmount
	}
	return 0
}

func (m *MDBond) GetWithdrawSellMoney() int64 {
	if m != nil {
		return m.WithdrawSellMoney
	}
	return 0
}

func (m *MDBond) GetTotalBuyNumber() int64 {
	if m != nil {
		return m.TotalBuyNumber
	}
	return 0
}

func (m *MDBond) GetTotalSellNumber() int64 {
	if m != nil {
		return m.TotalSellNumber
	}
	return 0
}

func (m *MDBond) GetBuyTradeMaxDuration() int64 {
	if m != nil {
		return m.BuyTradeMaxDuration
	}
	return 0
}

func (m *MDBond) GetSellTradeMaxDuration() int64 {
	if m != nil {
		return m.SellTradeMaxDuration
	}
	return 0
}

func (m *MDBond) GetNumBuyOrders() int32 {
	if m != nil {
		return m.NumBuyOrders
	}
	return 0
}

func (m *MDBond) GetNumSellOrders() int32 {
	if m != nil {
		return m.NumSellOrders
	}
	return 0
}

func (m *MDBond) GetYieldToMaturity() int64 {
	if m != nil {
		return m.YieldToMaturity
	}
	return 0
}

func (m *MDBond) GetWeightedAvgPx() int64 {
	if m != nil {
		return m.WeightedAvgPx
	}
	return 0
}

func (m *MDBond) GetWeightedAvgPxBP() int64 {
	if m != nil {
		return m.WeightedAvgPxBP
	}
	return 0
}

func (m *MDBond) GetPreCloseWeightedAvgPx() int64 {
	if m != nil {
		return m.PreCloseWeightedAvgPx
	}
	return 0
}

func (m *MDBond) GetExchangeDate() int32 {
	if m != nil {
		return m.ExchangeDate
	}
	return 0
}

func (m *MDBond) GetExchangeTime() int32 {
	if m != nil {
		return m.ExchangeTime
	}
	return 0
}

func (m *MDBond) GetPreCloseYield() int64 {
	if m != nil {
		return m.PreCloseYield
	}
	return 0
}

func (m *MDBond) GetPreWeightedAvgYield() int64 {
	if m != nil {
		return m.PreWeightedAvgYield
	}
	return 0
}

func (m *MDBond) GetOpenYield() int64 {
	if m != nil {
		return m.OpenYield
	}
	return 0
}

func (m *MDBond) GetHighYield() int64 {
	if m != nil {
		return m.HighYield
	}
	return 0
}

func (m *MDBond) GetLowYield() int64 {
	if m != nil {
		return m.LowYield
	}
	return 0
}

func (m *MDBond) GetLastYield() int64 {
	if m != nil {
		return m.LastYield
	}
	return 0
}

func (m *MDBond) GetWeightedAvgYield() int64 {
	if m != nil {
		return m.WeightedAvgYield
	}
	return 0
}

func (m *MDBond) GetChannelNo() int32 {
	if m != nil {
		return m.ChannelNo
	}
	return 0
}

func (m *MDBond) GetBuyPriceQueue() []int64 {
	if m != nil {
		return m.BuyPriceQueue
	}
	return nil
}

func (m *MDBond) GetBuyOrderQtyQueue() []int64 {
	if m != nil {
		return m.BuyOrderQtyQueue
	}
	return nil
}

func (m *MDBond) GetSellPriceQueue() []int64 {
	if m != nil {
		return m.SellPriceQueue
	}
	return nil
}

func (m *MDBond) GetSellOrderQtyQueue() []int64 {
	if m != nil {
		return m.SellOrderQtyQueue
	}
	return nil
}

func (m *MDBond) GetBuyOrderQueue() []int64 {
	if m != nil {
		return m.BuyOrderQueue
	}
	return nil
}

func (m *MDBond) GetSellOrderQueue() []int64 {
	if m != nil {
		return m.SellOrderQueue
	}
	return nil
}

func (m *MDBond) GetBuyNumOrdersQueue() []int64 {
	if m != nil {
		return m.BuyNumOrdersQueue
	}
	return nil
}

func (m *MDBond) GetSellNumOrdersQueue() []int64 {
	if m != nil {
		return m.SellNumOrdersQueue
	}
	return nil
}

func (m *MDBond) GetNorminalPx() int64 {
	if m != nil {
		return m.NorminalPx
	}
	return 0
}

func (m *MDBond) GetShortSellSharesTraded() int64 {
	if m != nil {
		return m.ShortSellSharesTraded
	}
	return 0
}

func (m *MDBond) GetShortSellTurnover() int64 {
	if m != nil {
		return m.ShortSellTurnover
	}
	return 0
}

func init() {
	proto.RegisterType((*MDBond)(nil), "com.htsc.mdc.insight.model.MDBond")
}

func init() { proto.RegisterFile("MDBond.proto", fileDescriptor_7d1e2a459aa62f2c) }

var fileDescriptor_7d1e2a459aa62f2c = []byte{
	// 967 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0xdf, 0x73, 0xd3, 0x46,
	0x10, 0x1e, 0x93, 0x26, 0x90, 0x23, 0x09, 0xc9, 0x25, 0xc0, 0xd5, 0xa5, 0xd4, 0xa4, 0x40, 0xdd,
	0x94, 0x8a, 0x60, 0xe8, 0xef, 0xf6, 0x01, 0xc5, 0x99, 0x49, 0x67, 0x62, 0xa3, 0xd8, 0x9e, 0x76,
	0xfa, 0x78, 0x58, 0x87, 0xad, 0x19, 0x4b, 0x97, 0x91, 0x74, 0x44, 0xfa, 0x6f, 0xfa, 0x67, 0xf6,
	0xb1, 0xb3, 0xbb, 0xfa, 0x2d, 0x0f, 0x6f, 0xde, 0xef, 0xfb, 0x76, 0xbd, 0xbb, 0x3a, 0x7d, 0x3a,
	0xb6, 0x33, 0x1a, 0xda, 0x3a, 0x70, 0xad, 0xeb, 0x50, 0xc7, 0x9a, 0x77, 0xe7, 0xda, 0xb7, 0x96,
	0x71, 0x34, 0xb7, 0x7c, 0x77, 0x6e, 0x79, 0x41, 0xe4, 0x2d, 0x96, 0xb1, 0xe5, 0x6b, 0x57, 0xad,
	0xba, 0x0f, 0xcf, 0xa7, 0x6a, 0x6e, 0x42, 0x2f, 0x4e, 0xff, 0x1c, 0x4e, 0xb5, 0x09, 0xe7, 0x8a,
	0x92, 0xba, 0x87, 0x05, 0x31, 0x4b, 0xaf, 0x33, 0xf0, 0xf8, 0x3f, 0xce, 0xb6, 0xa8, 0x34, 0x7f,
	0xce, 0xf6, 0x2e, 0x66, 0xd3, 0xb3, 0x32, 0x5b, 0x74, 0x7a, 0x9d, 0xfe, 0xf6, 0xa4, 0x81, 0xf2,
	0x07, 0x90, 0x31, 0x94, 0xb1, 0x12, 0xb7, 0x7a, 0x9d, 0xfe, 0xe6, 0x24, 0x8b, 0x08, 0x9f, 0x79,
	0xbe, 0x12, 0x1b, 0x39, 0x0e, 0x11, 0x7f, 0xca, 0x76, 0x87, 0x32, 0x96, 0xf0, 0x3b, 0x8a, 0xa5,
	0x7f, 0x2d, 0x3e, 0xeb, 0x75, 0xfa, 0x1b, 0x93, 0x3a, 0xc8, 0x4f, 0xd8, 0xfe, 0x2c, 0x94, 0xae,
	0x17, 0x2c, 0x9c, 0xa5, 0x8c, 0xd4, 0x99, 0x76, 0x95, 0xd8, 0xc4, 0xff, 0x6f, 0xe1, 0xfc, 0x8a,
	0xed, 0x47, 0x8d, 0x19, 0xc5, 0x56, 0xaf, 0xd3, 0xdf, 0x1b, 0x3c, 0xb3, 0x6a, 0x9b, 0xc1, 0x8d,
	0x58, 0xad, 0x85, 0x4c, 0x5a, 0xe9, 0xfc, 0x9c, 0xed, 0x44, 0x95, 0xed, 0x88, 0xdb, 0x58, 0xee,
	0xc9, 0x27, 0xcb, 0x81, 0x70, 0x52, 0x4b, 0xe3, 0x47, 0x6c, 0x73, 0x24, 0x13, 0x27, 0x11, 0x77,
	0x70, 0x46, 0x0a, 0x10, 0xf5, 0x02, 0x27, 0x11, 0xdb, 0x19, 0x0a, 0x01, 0x7f, 0xcc, 0x98, 0x13,
	0xaa, 0xb3, 0x95, 0x8e, 0x94, 0x93, 0x08, 0x86, 0x54, 0x05, 0xe1, 0x8f, 0xd8, 0xf6, 0xd8, 0xf8,
	0x30, 0xbc, 0x8a, 0xc4, 0x5d, 0xa4, 0x4b, 0x00, 0xf7, 0xa5, 0x63, 0xb9, 0xfa, 0x4b, 0xaf, 0x8c,
	0xaf, 0x10, 0x14, 0x3b, 0x28, 0x6a, 0xe1, 0xbc, 0xcf, 0xee, 0x11, 0x26, 0x57, 0x26, 0x93, 0xee,
	0xa2, 0xb4, 0x09, 0xc3, 0x33, 0xbc, 0x94, 0x51, 0xec, 0x24, 0x62, 0x0f, 0x05, 0x59, 0x04, 0xf8,
	0xbb, 0x6b, 0x05, 0x23, 0xdc, 0x23, 0x9c, 0x22, 0x2e, 0xd8, 0xed, 0x7c, 0x80, 0x7d, 0x24, 0xf2,
	0x10, 0x32, 0x2e, 0xbc, 0xc5, 0xd2, 0x49, 0xc4, 0x01, 0x65, 0x50, 0x04, 0xbb, 0xb8, 0xd4, 0x37,
	0x4e, 0x22, 0x38, 0xed, 0x02, 0x03, 0xa8, 0x33, 0xf4, 0x3e, 0x7c, 0x70, 0x92, 0x57, 0xe2, 0x90,
	0xea, 0x64, 0x61, 0xc9, 0x0c, 0xc4, 0x51, 0x95, 0x19, 0xf0, 0x1e, 0xbb, 0x8b, 0xed, 0xdb, 0x26,
	0xbd, 0x8a, 0x53, 0x71, 0x1f, 0xd9, 0x2a, 0xc4, 0x8f, 0xd9, 0x0e, 0x86, 0x53, 0xb5, 0x5a, 0x81,
	0xe4, 0x01, 0x4a, 0x6a, 0x18, 0xec, 0xf1, 0x6f, 0x05, 0xaf, 0x8f, 0x72, 0xdf, 0x7e, 0x5c, 0xd8,
	0x26, 0x75, 0x12, 0xf1, 0x90, 0xf6, 0xd8, 0xc4, 0xf9, 0x0b, 0x76, 0x50, 0xc1, 0xa0, 0x82, 0x93,
	0x08, 0x81, 0xe2, 0x36, 0x81, 0x6a, 0x2f, 0x5e, 0xba, 0xa1, 0xbc, 0xb1, 0x4d, 0x3a, 0x36, 0xfe,
	0x7b, 0x15, 0x8a, 0xcf, 0x33, 0x75, 0x93, 0x68, 0xa8, 0xdf, 0xfa, 0xda, 0x04, 0xb1, 0xe8, 0xb6,
	0xd4, 0x44, 0x60, 0xd7, 0x25, 0x38, 0xd2, 0x81, 0x4a, 0xc5, 0x17, 0x59, 0xd7, 0x0d, 0x9c, 0x5b,
	0x8c, 0xe7, 0x18, 0x74, 0x96, 0x35, 0xf2, 0x08, 0xd5, 0x6b, 0x98, 0xa6, 0x3e, 0x6b, 0xe5, 0xcb,
	0xb6, 0x3e, 0xeb, 0xa5, 0xd2, 0x39, 0xa0, 0xd4, 0xcc, 0xe3, 0x7a, 0xe7, 0x05, 0x01, 0x2e, 0x93,
	0x3f, 0xa2, 0xac, 0x93, 0xaf, 0x50, 0xda, 0x40, 0x8b, 0x33, 0x5b, 0x69, 0xb9, 0x57, 0x39, 0xb3,
	0x95, 0x7e, 0x4f, 0xd9, 0xa1, 0x6d, 0x52, 0x3c, 0xbf, 0x23, 0x99, 0x0c, 0x4d, 0x28, 0x63, 0x4f,
	0x07, 0xe2, 0x09, 0xaa, 0xd7, 0x51, 0x7c, 0xc0, 0x8e, 0x20, 0xbf, 0x95, 0x72, 0x8c, 0x29, 0x6b,
	0x39, 0x38, 0x4b, 0x63, 0xe3, 0xdb, 0x26, 0x7d, 0x17, 0xba, 0x2a, 0x8c, 0xc4, 0xd7, 0xe8, 0x71,
	0x35, 0x0c, 0x9c, 0x6e, 0x6c, 0x7c, 0x48, 0xcf, 0x44, 0x4f, 0x51, 0x54, 0x07, 0x61, 0xb2, 0x7f,
	0x3c, 0xb5, 0x72, 0x67, 0x7a, 0x24, 0x63, 0xb4, 0x0e, 0xf1, 0x8c, 0x26, 0x6b, 0xc0, 0x50, 0xaf,
	0x72, 0xac, 0x9c, 0x44, 0x3c, 0x27, 0xe7, 0xac, 0x81, 0x50, 0xaf, 0x06, 0xd8, 0x8e, 0xf8, 0x86,
	0xea, 0x35, 0x60, 0xfe, 0x86, 0xdd, 0xcf, 0xfd, 0xa5, 0x5e, 0xb7, 0x8f, 0xfa, 0xf5, 0x24, 0x4c,
	0x7e, 0x9e, 0xcc, 0x97, 0x32, 0x58, 0x28, 0x74, 0xfd, 0x6f, 0x69, 0xf2, 0x2a, 0x56, 0xd5, 0xe0,
	0x17, 0xe0, 0xa4, 0xae, 0xc9, 0xbf, 0x03, 0xf9, 0x1f, 0xe0, 0xa0, 0xe2, 0x3b, 0x9a, 0xa6, 0x06,
	0xc2, 0xd3, 0x74, 0xc2, 0x6a, 0x07, 0xa4, 0x7d, 0x41, 0x4f, 0x73, 0x0d, 0x05, 0x3e, 0x09, 0x6e,
	0x44, 0xba, 0xef, 0xc9, 0x27, 0x0b, 0x00, 0x58, 0x70, 0x1e, 0x62, 0x2d, 0x62, 0x0b, 0x80, 0x77,
	0xd9, 0x9d, 0x4b, 0x7d, 0x43, 0xe4, 0x4b, 0x24, 0x8b, 0x18, 0x32, 0xc1, 0xfd, 0x88, 0x3c, 0xa5,
	0xcc, 0x02, 0x68, 0xf8, 0x06, 0x89, 0x5e, 0xb5, 0x7c, 0xa3, 0xa8, 0x74, 0xb6, 0x94, 0x41, 0xa0,
	0x56, 0x63, 0x2d, 0x06, 0xb8, 0x9a, 0x12, 0xe0, 0x7d, 0xb6, 0x0b, 0xf6, 0x12, 0x7a, 0x73, 0x75,
	0x65, 0x94, 0x51, 0xe2, 0x75, 0x6f, 0xa3, 0xbf, 0x61, 0xdf, 0xda, 0xef, 0x4c, 0xea, 0x04, 0xb7,
	0xd8, 0x7e, 0x7e, 0xd8, 0xae, 0xe2, 0x94, 0xc4, 0x6f, 0x0a, 0x71, 0x8b, 0xe3, 0x27, 0x6c, 0x0f,
	0xbd, 0xa8, 0x2c, 0xfd, 0x43, 0xa1, 0x6e, 0x30, 0xfc, 0x94, 0x1d, 0x14, 0x67, 0xb4, 0x28, 0xfe,
	0x63, 0x21, 0x6f, 0x93, 0x59, 0xdf, 0x84, 0xa1, 0xfa, 0xa7, 0x5a, 0xdf, 0x25, 0x91, 0xf7, 0x51,
	0x91, 0xfe, 0x5c, 0xef, 0xa3, 0xa2, 0x3d, 0x65, 0x07, 0x64, 0x02, 0xf4, 0xb6, 0x90, 0xfc, 0x97,
	0xb2, 0x8f, 0x16, 0xc9, 0x07, 0x8c, 0x67, 0x6e, 0x50, 0x4d, 0xf9, 0xb5, 0x48, 0x59, 0xc3, 0xc2,
	0xb7, 0x77, 0xac, 0x43, 0xdf, 0x0b, 0x24, 0x58, 0xf8, 0x6f, 0xf4, 0xed, 0x2d, 0x11, 0x78, 0x53,
	0xa6, 0x4b, 0x1d, 0xc6, 0x90, 0x3a, 0x5d, 0xca, 0x50, 0x45, 0x68, 0x08, 0xae, 0xf8, 0x9d, 0xde,
	0x94, 0xb5, 0x24, 0x38, 0x61, 0x41, 0xcc, 0x4c, 0x18, 0xe8, 0x8f, 0x2a, 0x14, 0x7f, 0x90, 0x13,
	0xb6, 0x08, 0xfb, 0x25, 0xfb, 0xc4, 0x35, 0xce, 0xce, 0x2e, 0x7c, 0x0e, 0xdc, 0xd2, 0xa2, 0x8b,
	0xce, 0xbf, 0x9d, 0xce, 0xfb, 0x2d, 0xbc, 0xb2, 0xbd, 0xfe, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xc4,
	0x2e, 0xa5, 0xa4, 0x0c, 0x0a, 0x00, 0x00,
}
