// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MDOrder.proto

/*
Package com_htsc_mdc_insight_model is a generated protocol buffer package.

It is generated from these files:
	MDOrder.proto

It has these top-level messages:
	MDOrder
*/
package com_htsc_mdc_insight_model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 逐笔委托数据模型
type MDOrder struct {
	HTSCSecurityID   string            `protobuf:"bytes,1,opt,name=HTSCSecurityID" json:"HTSCSecurityID,omitempty"`
	MDDate           int32             `protobuf:"varint,2,opt,name=MDDate" json:"MDDate,omitempty"`
	MDTime           int32             `protobuf:"varint,3,opt,name=MDTime" json:"MDTime,omitempty"`
	DataTimestamp    int64             `protobuf:"varint,4,opt,name=DataTimestamp" json:"DataTimestamp,omitempty"`
	SecurityIDSource ESecurityIDSource `protobuf:"varint,5,opt,name=securityIDSource,enum=com.htsc.mdc.model.ESecurityIDSource" json:"securityIDSource,omitempty"`
	SecurityType     ESecurityType     `protobuf:"varint,6,opt,name=securityType,enum=com.htsc.mdc.model.ESecurityType" json:"securityType,omitempty"`
	OrderIndex       int64             `protobuf:"varint,7,opt,name=OrderIndex" json:"OrderIndex,omitempty"`
	OrderType        int32             `protobuf:"varint,8,opt,name=OrderType" json:"OrderType,omitempty"`
	OrderPrice       int64             `protobuf:"varint,9,opt,name=OrderPrice" json:"OrderPrice,omitempty"`
	OrderQty         int64             `protobuf:"varint,10,opt,name=OrderQty" json:"OrderQty,omitempty"`
	OrderBSFlag      int32             `protobuf:"varint,11,opt,name=OrderBSFlag" json:"OrderBSFlag,omitempty"`
}

func (m *MDOrder) Reset()         { *m = MDOrder{} }
func (m *MDOrder) String() string { return proto.CompactTextString(m) }
func (*MDOrder) ProtoMessage()    {}

func (m *MDOrder) GetHTSCSecurityID() string {
	if m != nil {
		return m.HTSCSecurityID
	}
	return ""
}

func (m *MDOrder) GetMDDate() int32 {
	if m != nil {
		return m.MDDate
	}
	return 0
}

func (m *MDOrder) GetMDTime() int32 {
	if m != nil {
		return m.MDTime
	}
	return 0
}

func (m *MDOrder) GetDataTimestamp() int64 {
	if m != nil {
		return m.DataTimestamp
	}
	return 0
}

func (m *MDOrder) GetSecurityIDSource() ESecurityIDSource {
	if m != nil {
		return m.SecurityIDSource
	}
	return ESecurityIDSource_DefaultSecurityIDSource
}

func (m *MDOrder) GetSecurityType() ESecurityType {
	if m != nil {
		return m.SecurityType
	}
	return ESecurityType_DefaultSecurityType
}

func (m *MDOrder) GetOrderIndex() int64 {
	if m != nil {
		return m.OrderIndex
	}
	return 0
}

func (m *MDOrder) GetOrderType() int32 {
	if m != nil {
		return m.OrderType
	}
	return 0
}

func (m *MDOrder) GetOrderPrice() int64 {
	if m != nil {
		return m.OrderPrice
	}
	return 0
}

func (m *MDOrder) GetOrderQty() int64 {
	if m != nil {
		return m.OrderQty
	}
	return 0
}

func (m *MDOrder) GetOrderBSFlag() int32 {
	if m != nil {
		return m.OrderBSFlag
	}
	return 0
}

func init() {
	proto.RegisterType((*MDOrder)(nil), "com.htsc.mdc.insight.model.MDOrder")
}
