// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transactionData.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "transactionData.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace comm {

namespace {

const ::google::protobuf::Descriptor* TransactionData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TransactionData_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_transactionData_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_transactionData_2eproto() {
  protobuf_AddDesc_transactionData_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "transactionData.proto");
  GOOGLE_CHECK(file != NULL);
  TransactionData_descriptor_ = file->message_type(0);
  static const int TransactionData_offsets_[13] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, windcode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, actionday_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, index_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, price_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, volume_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, turnover_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, bsflag_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, orderkind_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, functioncode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, askorder_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, bidorder_),
  };
  TransactionData_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TransactionData_descriptor_,
      TransactionData::internal_default_instance(),
      TransactionData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, _has_bits_),
      -1,
      -1,
      sizeof(TransactionData),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransactionData, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_transactionData_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TransactionData_descriptor_, TransactionData::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_transactionData_2eproto() {
  TransactionData_default_instance_.Shutdown();
  delete TransactionData_reflection_;
}

void protobuf_InitDefaults_transactionData_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  TransactionData_default_instance_.DefaultConstruct();
  TransactionData_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_transactionData_2eproto_once_);
void protobuf_InitDefaults_transactionData_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_transactionData_2eproto_once_,
                 &protobuf_InitDefaults_transactionData_2eproto_impl);
}
void protobuf_AddDesc_transactionData_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_transactionData_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025transactionData.proto\022\004comm\"\357\001\n\017Transa"
    "ctionData\022\020\n\010WindCode\030\001 \002(\t\022\014\n\004Code\030\002 \002("
    "\t\022\021\n\tActionDay\030\003 \002(\005\022\014\n\004Time\030\004 \002(\005\022\r\n\005In"
    "dex\030\005 \002(\005\022\r\n\005Price\030\006 \002(\005\022\016\n\006Volume\030\007 \002(\005"
    "\022\020\n\010Turnover\030\010 \002(\005\022\016\n\006BSFlag\030\t \002(\005\022\021\n\tOr"
    "derKind\030\n \002(\t\022\024\n\014FunctionCode\030\013 \002(\t\022\020\n\010A"
    "skOrder\030\014 \002(\005\022\020\n\010BidOrder\030\r \002(\005", 271);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "transactionData.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_transactionData_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_transactionData_2eproto_once_);
void protobuf_AddDesc_transactionData_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_transactionData_2eproto_once_,
                 &protobuf_AddDesc_transactionData_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_transactionData_2eproto {
  StaticDescriptorInitializer_transactionData_2eproto() {
    protobuf_AddDesc_transactionData_2eproto();
  }
} static_descriptor_initializer_transactionData_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TransactionData::kWindCodeFieldNumber;
const int TransactionData::kCodeFieldNumber;
const int TransactionData::kActionDayFieldNumber;
const int TransactionData::kTimeFieldNumber;
const int TransactionData::kIndexFieldNumber;
const int TransactionData::kPriceFieldNumber;
const int TransactionData::kVolumeFieldNumber;
const int TransactionData::kTurnoverFieldNumber;
const int TransactionData::kBSFlagFieldNumber;
const int TransactionData::kOrderKindFieldNumber;
const int TransactionData::kFunctionCodeFieldNumber;
const int TransactionData::kAskOrderFieldNumber;
const int TransactionData::kBidOrderFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TransactionData::TransactionData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_transactionData_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:comm.TransactionData)
}

void TransactionData::InitAsDefaultInstance() {
}

TransactionData::TransactionData(const TransactionData& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:comm.TransactionData)
}

void TransactionData::SharedCtor() {
  _cached_size_ = 0;
  windcode_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  code_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  orderkind_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  functioncode_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&actionday_, 0, reinterpret_cast<char*>(&bidorder_) -
    reinterpret_cast<char*>(&actionday_) + sizeof(bidorder_));
}

TransactionData::~TransactionData() {
  // @@protoc_insertion_point(destructor:comm.TransactionData)
  SharedDtor();
}

void TransactionData::SharedDtor() {
  windcode_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  code_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  orderkind_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  functioncode_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void TransactionData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TransactionData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TransactionData_descriptor_;
}

const TransactionData& TransactionData::default_instance() {
  protobuf_InitDefaults_transactionData_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<TransactionData> TransactionData_default_instance_;

TransactionData* TransactionData::New(::google::protobuf::Arena* arena) const {
  TransactionData* n = new TransactionData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TransactionData::Clear() {
// @@protoc_insertion_point(message_clear_start:comm.TransactionData)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(TransactionData, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<TransactionData*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&(first), 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 255u) {
    ZR_(actionday_, turnover_);
    if (has_windcode()) {
      windcode_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_code()) {
      code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  if (_has_bits_[8 / 32] & 7936u) {
    ZR_(bsflag_, bidorder_);
    if (has_orderkind()) {
      orderkind_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_functioncode()) {
      functioncode_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }

#undef ZR_HELPER_
#undef ZR_

  _has_bits_.Clear();
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool TransactionData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:comm.TransactionData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string WindCode = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_windcode()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->windcode().data(), this->windcode().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "comm.TransactionData.WindCode");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_Code;
        break;
      }

      // required string Code = 2;
      case 2: {
        if (tag == 18) {
         parse_Code:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_code()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->code().data(), this->code().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "comm.TransactionData.Code");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_ActionDay;
        break;
      }

      // required int32 ActionDay = 3;
      case 3: {
        if (tag == 24) {
         parse_ActionDay:
          set_has_actionday();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &actionday_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_Time;
        break;
      }

      // required int32 Time = 4;
      case 4: {
        if (tag == 32) {
         parse_Time:
          set_has_time();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &time_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_Index;
        break;
      }

      // required int32 Index = 5;
      case 5: {
        if (tag == 40) {
         parse_Index:
          set_has_index();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &index_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_Price;
        break;
      }

      // required int32 Price = 6;
      case 6: {
        if (tag == 48) {
         parse_Price:
          set_has_price();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &price_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_Volume;
        break;
      }

      // required int32 Volume = 7;
      case 7: {
        if (tag == 56) {
         parse_Volume:
          set_has_volume();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &volume_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_Turnover;
        break;
      }

      // required int32 Turnover = 8;
      case 8: {
        if (tag == 64) {
         parse_Turnover:
          set_has_turnover();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &turnover_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(72)) goto parse_BSFlag;
        break;
      }

      // required int32 BSFlag = 9;
      case 9: {
        if (tag == 72) {
         parse_BSFlag:
          set_has_bsflag();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &bsflag_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_OrderKind;
        break;
      }

      // required string OrderKind = 10;
      case 10: {
        if (tag == 82) {
         parse_OrderKind:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_orderkind()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->orderkind().data(), this->orderkind().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "comm.TransactionData.OrderKind");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_FunctionCode;
        break;
      }

      // required string FunctionCode = 11;
      case 11: {
        if (tag == 90) {
         parse_FunctionCode:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_functioncode()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->functioncode().data(), this->functioncode().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "comm.TransactionData.FunctionCode");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(96)) goto parse_AskOrder;
        break;
      }

      // required int32 AskOrder = 12;
      case 12: {
        if (tag == 96) {
         parse_AskOrder:
          set_has_askorder();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &askorder_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(104)) goto parse_BidOrder;
        break;
      }

      // required int32 BidOrder = 13;
      case 13: {
        if (tag == 104) {
         parse_BidOrder:
          set_has_bidorder();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &bidorder_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:comm.TransactionData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:comm.TransactionData)
  return false;
#undef DO_
}

void TransactionData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:comm.TransactionData)
  // required string WindCode = 1;
  if (has_windcode()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->windcode().data(), this->windcode().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "comm.TransactionData.WindCode");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->windcode(), output);
  }

  // required string Code = 2;
  if (has_code()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->code().data(), this->code().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "comm.TransactionData.Code");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->code(), output);
  }

  // required int32 ActionDay = 3;
  if (has_actionday()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->actionday(), output);
  }

  // required int32 Time = 4;
  if (has_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->time(), output);
  }

  // required int32 Index = 5;
  if (has_index()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->index(), output);
  }

  // required int32 Price = 6;
  if (has_price()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->price(), output);
  }

  // required int32 Volume = 7;
  if (has_volume()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->volume(), output);
  }

  // required int32 Turnover = 8;
  if (has_turnover()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->turnover(), output);
  }

  // required int32 BSFlag = 9;
  if (has_bsflag()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->bsflag(), output);
  }

  // required string OrderKind = 10;
  if (has_orderkind()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->orderkind().data(), this->orderkind().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "comm.TransactionData.OrderKind");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->orderkind(), output);
  }

  // required string FunctionCode = 11;
  if (has_functioncode()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->functioncode().data(), this->functioncode().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "comm.TransactionData.FunctionCode");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->functioncode(), output);
  }

  // required int32 AskOrder = 12;
  if (has_askorder()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(12, this->askorder(), output);
  }

  // required int32 BidOrder = 13;
  if (has_bidorder()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(13, this->bidorder(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:comm.TransactionData)
}

::google::protobuf::uint8* TransactionData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:comm.TransactionData)
  // required string WindCode = 1;
  if (has_windcode()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->windcode().data(), this->windcode().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "comm.TransactionData.WindCode");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->windcode(), target);
  }

  // required string Code = 2;
  if (has_code()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->code().data(), this->code().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "comm.TransactionData.Code");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->code(), target);
  }

  // required int32 ActionDay = 3;
  if (has_actionday()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->actionday(), target);
  }

  // required int32 Time = 4;
  if (has_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->time(), target);
  }

  // required int32 Index = 5;
  if (has_index()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->index(), target);
  }

  // required int32 Price = 6;
  if (has_price()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->price(), target);
  }

  // required int32 Volume = 7;
  if (has_volume()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->volume(), target);
  }

  // required int32 Turnover = 8;
  if (has_turnover()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->turnover(), target);
  }

  // required int32 BSFlag = 9;
  if (has_bsflag()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->bsflag(), target);
  }

  // required string OrderKind = 10;
  if (has_orderkind()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->orderkind().data(), this->orderkind().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "comm.TransactionData.OrderKind");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->orderkind(), target);
  }

  // required string FunctionCode = 11;
  if (has_functioncode()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->functioncode().data(), this->functioncode().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "comm.TransactionData.FunctionCode");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->functioncode(), target);
  }

  // required int32 AskOrder = 12;
  if (has_askorder()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(12, this->askorder(), target);
  }

  // required int32 BidOrder = 13;
  if (has_bidorder()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(13, this->bidorder(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:comm.TransactionData)
  return target;
}

size_t TransactionData::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:comm.TransactionData)
  size_t total_size = 0;

  if (has_windcode()) {
    // required string WindCode = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->windcode());
  }

  if (has_code()) {
    // required string Code = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->code());
  }

  if (has_actionday()) {
    // required int32 ActionDay = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->actionday());
  }

  if (has_time()) {
    // required int32 Time = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->time());
  }

  if (has_index()) {
    // required int32 Index = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->index());
  }

  if (has_price()) {
    // required int32 Price = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->price());
  }

  if (has_volume()) {
    // required int32 Volume = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->volume());
  }

  if (has_turnover()) {
    // required int32 Turnover = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->turnover());
  }

  if (has_bsflag()) {
    // required int32 BSFlag = 9;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->bsflag());
  }

  if (has_orderkind()) {
    // required string OrderKind = 10;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->orderkind());
  }

  if (has_functioncode()) {
    // required string FunctionCode = 11;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->functioncode());
  }

  if (has_askorder()) {
    // required int32 AskOrder = 12;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->askorder());
  }

  if (has_bidorder()) {
    // required int32 BidOrder = 13;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->bidorder());
  }

  return total_size;
}
size_t TransactionData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:comm.TransactionData)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00001fff) ^ 0x00001fff) == 0) {  // All required fields are present.
    // required string WindCode = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->windcode());

    // required string Code = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->code());

    // required int32 ActionDay = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->actionday());

    // required int32 Time = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->time());

    // required int32 Index = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->index());

    // required int32 Price = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->price());

    // required int32 Volume = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->volume());

    // required int32 Turnover = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->turnover());

    // required int32 BSFlag = 9;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->bsflag());

    // required string OrderKind = 10;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->orderkind());

    // required string FunctionCode = 11;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->functioncode());

    // required int32 AskOrder = 12;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->askorder());

    // required int32 BidOrder = 13;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->bidorder());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TransactionData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:comm.TransactionData)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const TransactionData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TransactionData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:comm.TransactionData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:comm.TransactionData)
    UnsafeMergeFrom(*source);
  }
}

void TransactionData::MergeFrom(const TransactionData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:comm.TransactionData)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void TransactionData::UnsafeMergeFrom(const TransactionData& from) {
  GOOGLE_DCHECK(&from != this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_windcode()) {
      set_has_windcode();
      windcode_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.windcode_);
    }
    if (from.has_code()) {
      set_has_code();
      code_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.code_);
    }
    if (from.has_actionday()) {
      set_actionday(from.actionday());
    }
    if (from.has_time()) {
      set_time(from.time());
    }
    if (from.has_index()) {
      set_index(from.index());
    }
    if (from.has_price()) {
      set_price(from.price());
    }
    if (from.has_volume()) {
      set_volume(from.volume());
    }
    if (from.has_turnover()) {
      set_turnover(from.turnover());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_bsflag()) {
      set_bsflag(from.bsflag());
    }
    if (from.has_orderkind()) {
      set_has_orderkind();
      orderkind_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.orderkind_);
    }
    if (from.has_functioncode()) {
      set_has_functioncode();
      functioncode_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.functioncode_);
    }
    if (from.has_askorder()) {
      set_askorder(from.askorder());
    }
    if (from.has_bidorder()) {
      set_bidorder(from.bidorder());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::UnknownFieldSet::MergeToInternalMetdata(
      from.unknown_fields(), &_internal_metadata_);
  }
}

void TransactionData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:comm.TransactionData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TransactionData::CopyFrom(const TransactionData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:comm.TransactionData)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool TransactionData::IsInitialized() const {
  if ((_has_bits_[0] & 0x00001fff) != 0x00001fff) return false;

  return true;
}

void TransactionData::Swap(TransactionData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TransactionData::InternalSwap(TransactionData* other) {
  windcode_.Swap(&other->windcode_);
  code_.Swap(&other->code_);
  std::swap(actionday_, other->actionday_);
  std::swap(time_, other->time_);
  std::swap(index_, other->index_);
  std::swap(price_, other->price_);
  std::swap(volume_, other->volume_);
  std::swap(turnover_, other->turnover_);
  std::swap(bsflag_, other->bsflag_);
  orderkind_.Swap(&other->orderkind_);
  functioncode_.Swap(&other->functioncode_);
  std::swap(askorder_, other->askorder_);
  std::swap(bidorder_, other->bidorder_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TransactionData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TransactionData_descriptor_;
  metadata.reflection = TransactionData_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TransactionData

// required string WindCode = 1;
bool TransactionData::has_windcode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void TransactionData::set_has_windcode() {
  _has_bits_[0] |= 0x00000001u;
}
void TransactionData::clear_has_windcode() {
  _has_bits_[0] &= ~0x00000001u;
}
void TransactionData::clear_windcode() {
  windcode_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_windcode();
}
const ::std::string& TransactionData::windcode() const {
  // @@protoc_insertion_point(field_get:comm.TransactionData.WindCode)
  return windcode_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TransactionData::set_windcode(const ::std::string& value) {
  set_has_windcode();
  windcode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:comm.TransactionData.WindCode)
}
void TransactionData::set_windcode(const char* value) {
  set_has_windcode();
  windcode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:comm.TransactionData.WindCode)
}
void TransactionData::set_windcode(const char* value, size_t size) {
  set_has_windcode();
  windcode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:comm.TransactionData.WindCode)
}
::std::string* TransactionData::mutable_windcode() {
  set_has_windcode();
  // @@protoc_insertion_point(field_mutable:comm.TransactionData.WindCode)
  return windcode_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* TransactionData::release_windcode() {
  // @@protoc_insertion_point(field_release:comm.TransactionData.WindCode)
  clear_has_windcode();
  return windcode_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TransactionData::set_allocated_windcode(::std::string* windcode) {
  if (windcode != NULL) {
    set_has_windcode();
  } else {
    clear_has_windcode();
  }
  windcode_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), windcode);
  // @@protoc_insertion_point(field_set_allocated:comm.TransactionData.WindCode)
}

// required string Code = 2;
bool TransactionData::has_code() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void TransactionData::set_has_code() {
  _has_bits_[0] |= 0x00000002u;
}
void TransactionData::clear_has_code() {
  _has_bits_[0] &= ~0x00000002u;
}
void TransactionData::clear_code() {
  code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_code();
}
const ::std::string& TransactionData::code() const {
  // @@protoc_insertion_point(field_get:comm.TransactionData.Code)
  return code_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TransactionData::set_code(const ::std::string& value) {
  set_has_code();
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:comm.TransactionData.Code)
}
void TransactionData::set_code(const char* value) {
  set_has_code();
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:comm.TransactionData.Code)
}
void TransactionData::set_code(const char* value, size_t size) {
  set_has_code();
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:comm.TransactionData.Code)
}
::std::string* TransactionData::mutable_code() {
  set_has_code();
  // @@protoc_insertion_point(field_mutable:comm.TransactionData.Code)
  return code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* TransactionData::release_code() {
  // @@protoc_insertion_point(field_release:comm.TransactionData.Code)
  clear_has_code();
  return code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TransactionData::set_allocated_code(::std::string* code) {
  if (code != NULL) {
    set_has_code();
  } else {
    clear_has_code();
  }
  code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), code);
  // @@protoc_insertion_point(field_set_allocated:comm.TransactionData.Code)
}

// required int32 ActionDay = 3;
bool TransactionData::has_actionday() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void TransactionData::set_has_actionday() {
  _has_bits_[0] |= 0x00000004u;
}
void TransactionData::clear_has_actionday() {
  _has_bits_[0] &= ~0x00000004u;
}
void TransactionData::clear_actionday() {
  actionday_ = 0;
  clear_has_actionday();
}
::google::protobuf::int32 TransactionData::actionday() const {
  // @@protoc_insertion_point(field_get:comm.TransactionData.ActionDay)
  return actionday_;
}
void TransactionData::set_actionday(::google::protobuf::int32 value) {
  set_has_actionday();
  actionday_ = value;
  // @@protoc_insertion_point(field_set:comm.TransactionData.ActionDay)
}

// required int32 Time = 4;
bool TransactionData::has_time() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void TransactionData::set_has_time() {
  _has_bits_[0] |= 0x00000008u;
}
void TransactionData::clear_has_time() {
  _has_bits_[0] &= ~0x00000008u;
}
void TransactionData::clear_time() {
  time_ = 0;
  clear_has_time();
}
::google::protobuf::int32 TransactionData::time() const {
  // @@protoc_insertion_point(field_get:comm.TransactionData.Time)
  return time_;
}
void TransactionData::set_time(::google::protobuf::int32 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:comm.TransactionData.Time)
}

// required int32 Index = 5;
bool TransactionData::has_index() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void TransactionData::set_has_index() {
  _has_bits_[0] |= 0x00000010u;
}
void TransactionData::clear_has_index() {
  _has_bits_[0] &= ~0x00000010u;
}
void TransactionData::clear_index() {
  index_ = 0;
  clear_has_index();
}
::google::protobuf::int32 TransactionData::index() const {
  // @@protoc_insertion_point(field_get:comm.TransactionData.Index)
  return index_;
}
void TransactionData::set_index(::google::protobuf::int32 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:comm.TransactionData.Index)
}

// required int32 Price = 6;
bool TransactionData::has_price() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void TransactionData::set_has_price() {
  _has_bits_[0] |= 0x00000020u;
}
void TransactionData::clear_has_price() {
  _has_bits_[0] &= ~0x00000020u;
}
void TransactionData::clear_price() {
  price_ = 0;
  clear_has_price();
}
::google::protobuf::int32 TransactionData::price() const {
  // @@protoc_insertion_point(field_get:comm.TransactionData.Price)
  return price_;
}
void TransactionData::set_price(::google::protobuf::int32 value) {
  set_has_price();
  price_ = value;
  // @@protoc_insertion_point(field_set:comm.TransactionData.Price)
}

// required int32 Volume = 7;
bool TransactionData::has_volume() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void TransactionData::set_has_volume() {
  _has_bits_[0] |= 0x00000040u;
}
void TransactionData::clear_has_volume() {
  _has_bits_[0] &= ~0x00000040u;
}
void TransactionData::clear_volume() {
  volume_ = 0;
  clear_has_volume();
}
::google::protobuf::int32 TransactionData::volume() const {
  // @@protoc_insertion_point(field_get:comm.TransactionData.Volume)
  return volume_;
}
void TransactionData::set_volume(::google::protobuf::int32 value) {
  set_has_volume();
  volume_ = value;
  // @@protoc_insertion_point(field_set:comm.TransactionData.Volume)
}

// required int32 Turnover = 8;
bool TransactionData::has_turnover() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void TransactionData::set_has_turnover() {
  _has_bits_[0] |= 0x00000080u;
}
void TransactionData::clear_has_turnover() {
  _has_bits_[0] &= ~0x00000080u;
}
void TransactionData::clear_turnover() {
  turnover_ = 0;
  clear_has_turnover();
}
::google::protobuf::int32 TransactionData::turnover() const {
  // @@protoc_insertion_point(field_get:comm.TransactionData.Turnover)
  return turnover_;
}
void TransactionData::set_turnover(::google::protobuf::int32 value) {
  set_has_turnover();
  turnover_ = value;
  // @@protoc_insertion_point(field_set:comm.TransactionData.Turnover)
}

// required int32 BSFlag = 9;
bool TransactionData::has_bsflag() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
void TransactionData::set_has_bsflag() {
  _has_bits_[0] |= 0x00000100u;
}
void TransactionData::clear_has_bsflag() {
  _has_bits_[0] &= ~0x00000100u;
}
void TransactionData::clear_bsflag() {
  bsflag_ = 0;
  clear_has_bsflag();
}
::google::protobuf::int32 TransactionData::bsflag() const {
  // @@protoc_insertion_point(field_get:comm.TransactionData.BSFlag)
  return bsflag_;
}
void TransactionData::set_bsflag(::google::protobuf::int32 value) {
  set_has_bsflag();
  bsflag_ = value;
  // @@protoc_insertion_point(field_set:comm.TransactionData.BSFlag)
}

// required string OrderKind = 10;
bool TransactionData::has_orderkind() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
void TransactionData::set_has_orderkind() {
  _has_bits_[0] |= 0x00000200u;
}
void TransactionData::clear_has_orderkind() {
  _has_bits_[0] &= ~0x00000200u;
}
void TransactionData::clear_orderkind() {
  orderkind_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_orderkind();
}
const ::std::string& TransactionData::orderkind() const {
  // @@protoc_insertion_point(field_get:comm.TransactionData.OrderKind)
  return orderkind_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TransactionData::set_orderkind(const ::std::string& value) {
  set_has_orderkind();
  orderkind_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:comm.TransactionData.OrderKind)
}
void TransactionData::set_orderkind(const char* value) {
  set_has_orderkind();
  orderkind_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:comm.TransactionData.OrderKind)
}
void TransactionData::set_orderkind(const char* value, size_t size) {
  set_has_orderkind();
  orderkind_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:comm.TransactionData.OrderKind)
}
::std::string* TransactionData::mutable_orderkind() {
  set_has_orderkind();
  // @@protoc_insertion_point(field_mutable:comm.TransactionData.OrderKind)
  return orderkind_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* TransactionData::release_orderkind() {
  // @@protoc_insertion_point(field_release:comm.TransactionData.OrderKind)
  clear_has_orderkind();
  return orderkind_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TransactionData::set_allocated_orderkind(::std::string* orderkind) {
  if (orderkind != NULL) {
    set_has_orderkind();
  } else {
    clear_has_orderkind();
  }
  orderkind_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), orderkind);
  // @@protoc_insertion_point(field_set_allocated:comm.TransactionData.OrderKind)
}

// required string FunctionCode = 11;
bool TransactionData::has_functioncode() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
void TransactionData::set_has_functioncode() {
  _has_bits_[0] |= 0x00000400u;
}
void TransactionData::clear_has_functioncode() {
  _has_bits_[0] &= ~0x00000400u;
}
void TransactionData::clear_functioncode() {
  functioncode_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_functioncode();
}
const ::std::string& TransactionData::functioncode() const {
  // @@protoc_insertion_point(field_get:comm.TransactionData.FunctionCode)
  return functioncode_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TransactionData::set_functioncode(const ::std::string& value) {
  set_has_functioncode();
  functioncode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:comm.TransactionData.FunctionCode)
}
void TransactionData::set_functioncode(const char* value) {
  set_has_functioncode();
  functioncode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:comm.TransactionData.FunctionCode)
}
void TransactionData::set_functioncode(const char* value, size_t size) {
  set_has_functioncode();
  functioncode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:comm.TransactionData.FunctionCode)
}
::std::string* TransactionData::mutable_functioncode() {
  set_has_functioncode();
  // @@protoc_insertion_point(field_mutable:comm.TransactionData.FunctionCode)
  return functioncode_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* TransactionData::release_functioncode() {
  // @@protoc_insertion_point(field_release:comm.TransactionData.FunctionCode)
  clear_has_functioncode();
  return functioncode_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TransactionData::set_allocated_functioncode(::std::string* functioncode) {
  if (functioncode != NULL) {
    set_has_functioncode();
  } else {
    clear_has_functioncode();
  }
  functioncode_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), functioncode);
  // @@protoc_insertion_point(field_set_allocated:comm.TransactionData.FunctionCode)
}

// required int32 AskOrder = 12;
bool TransactionData::has_askorder() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
void TransactionData::set_has_askorder() {
  _has_bits_[0] |= 0x00000800u;
}
void TransactionData::clear_has_askorder() {
  _has_bits_[0] &= ~0x00000800u;
}
void TransactionData::clear_askorder() {
  askorder_ = 0;
  clear_has_askorder();
}
::google::protobuf::int32 TransactionData::askorder() const {
  // @@protoc_insertion_point(field_get:comm.TransactionData.AskOrder)
  return askorder_;
}
void TransactionData::set_askorder(::google::protobuf::int32 value) {
  set_has_askorder();
  askorder_ = value;
  // @@protoc_insertion_point(field_set:comm.TransactionData.AskOrder)
}

// required int32 BidOrder = 13;
bool TransactionData::has_bidorder() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
void TransactionData::set_has_bidorder() {
  _has_bits_[0] |= 0x00001000u;
}
void TransactionData::clear_has_bidorder() {
  _has_bits_[0] &= ~0x00001000u;
}
void TransactionData::clear_bidorder() {
  bidorder_ = 0;
  clear_has_bidorder();
}
::google::protobuf::int32 TransactionData::bidorder() const {
  // @@protoc_insertion_point(field_get:comm.TransactionData.BidOrder)
  return bidorder_;
}
void TransactionData::set_bidorder(::google::protobuf::int32 value) {
  set_has_bidorder();
  bidorder_ = value;
  // @@protoc_insertion_point(field_set:comm.TransactionData.BidOrder)
}

inline const TransactionData* TransactionData::internal_default_instance() {
  return &TransactionData_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace comm

// @@protoc_insertion_point(global_scope)
